version: '3.9'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'
  queue:
    image: rabbitmq:3
    ports:
      - '5672:5672'
  celeryworker:
    build:
      context: '.'
      dockerfile: celeryworker.dockerfile
    depends_on:
      - queue
    environment:
      CELERY_BROKER_URL: 'amqp://guest@queue//'
  prod-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
  prod-redis:
    image: redis:6-alpine
  test-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54320:5432'
  app:
    build:
      context: '.'
      dockerfile: backend.dockerfile
    depends_on:
      - celeryworker
      - mailhog
      - prod-db
      - prod-redis
    environment:
      DEBUG: 0
      REDIS_URL: 'redis://prod-redis/0'
      SQLALCHEMY_DATABASE_URL: 'postgresql+asyncpg://postgres:postgres@prod-db/postgres'
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_TLS: 0
      CELERY_BROKER_URL: 'amqp://guest@queue//'
    ports:
      - '8000:80'
    command: ["./docker/wait-for-it.sh", "prod-db:5432", "--", "./docker/runserver.sh"]